Agreeableness = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\Agreeableness.csv",head=TRUE,sep=","))
Conscientiousness = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\Conscientiousness.csv",head=TRUE,sep=","))
EnvFocus = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\EnvFocus.csv",head=TRUE,sep=","))
Extraversion = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\Extraversion.csv",head=TRUE,sep=","))
GPA = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\GPA.csv",head=TRUE,sep=","))
IntExtRating = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\IntExtRating.csv",head=TRUE,sep=","))
VFICareer = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\VFICareer.csv",head=TRUE,sep=","))
Neurotocism = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\Neurotocism.csv",head=TRUE,sep=","))
Openness = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\Openness.csv",head=TRUE,sep=","))
OPFocus = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\OPFocus.csv",head=TRUE,sep=","))
OverallRating = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\OverallRating.csv",head=TRUE,sep=","))
OverallFuture = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\OverallFuture.csv",head=TRUE,sep=","))
OverallDaily = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\OverallDaily.csv",head=TRUE,sep=","))
ProAttRating = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\ProAttRating.csv",head=TRUE,sep=","))
ProEnvironment = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\ProEnvironment.csv",head=TRUE,sep=","))
ProsocialPersonality = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\ProsocialPersonality.csv",head=TRUE,sep=","))
WordCount = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\WordCount.csv",head=TRUE,sep=","))
WritingRating = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\WritingRating.csv",head=TRUE,sep=","))
WritingFuture = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\WritingFuture.csv",head=TRUE,sep=","))
WritingDaily = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\WritingDaily.csv",head=TRUE,sep=","))
PastPositive = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\PastPositive.csv",head=TRUE,sep=","))
PastNegative = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\PastNegative.csv",head=TRUE,sep=","))
FuturePerspective = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\FuturePerspective.csv",head=TRUE,sep=","))
PresentFatalistic = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\PresentFatalistic.csv",head=TRUE,sep=","))
PresentHedonistic = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\PresentHedonistic.csv",head=TRUE,sep=","))
VolPY = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\VolPY.csv",head=TRUE,sep=","))
VolCurrent = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\VolCurrent.csv",head=TRUE,sep=","))

WritT = as.matrix(rowMeans(WritingRating, na.rm = TRUE, dims = 1))
WritFT = as.matrix(rowMeans(WritingFuture, na.rm = TRUE, dims = 1))
WritDT = as.matrix(rowMeans(WritingDaily, na.rm = TRUE, dims = 1))
OverT = as.matrix(rowMeans(OverallRating, na.rm = TRUE, dims = 1))
OverFT = as.matrix(rowMeans(OverallFuture, na.rm = TRUE, dims = 1))
OverDT = as.matrix(rowMeans(OverallDaily, na.rm = TRUE, dims = 1))
ProAT = as.matrix(rowMeans(ProAttRating, na.rm = TRUE, dims = 1))
EnvFT = as.matrix(rowMeans(EnvFocus, na.rm = TRUE, dims = 1))
OPFT = as.matrix(rowMeans(OPFocus, na.rm = TRUE, dims = 1))
IERT = as.matrix(rowMeans(IntExtRating, na.rm = TRUE, dims = 1))
ProET = as.matrix(rowMeans(ProEnvironment, na.rm = TRUE, dims = 1))
ProSocT = as.matrix(rowMeans(ProsocialPersonality, na.rm = TRUE, dims = 1))
PPT = as.matrix(rowMeans(PastPositive, na.rm = TRUE, dims = 1))
PNT = as.matrix(rowMeans(PastNegative, na.rm = TRUE, dims = 1))
FPT = as.matrix(rowMeans(FuturePerspective, na.rm = TRUE, dims = 1))
PFT = as.matrix(rowMeans(PresentFatalistic, na.rm = TRUE, dims = 1))
PHT = as.matrix(rowMeans(PresentHedonistic, na.rm = TRUE, dims = 1))
OpenT = as.matrix(rowMeans(Openness, na.rm = TRUE, dims = 1))
ConscT = as.matrix(rowMeans(Conscientiousness, na.rm = TRUE, dims = 1))
ExtraT = as.matrix(rowMeans(Extraversion, na.rm = TRUE, dims = 1))
AgreeT = as.matrix(rowMeans(Agreeableness, na.rm = TRUE, dims = 1))
NeuroT = as.matrix(rowMeans(Neurotocism, na.rm = TRUE, dims = 1))
VFICT = as.matrix(rowMeans(VFICareer, na.rm = TRUE, dims = 1))

sink("describe.txt")
describe(WordCount)
sink()
sink("describe2.txt")
describe(VolPY)
describe(VolCurrent)
sink()
sink("describe3.txt")
describe(NeuroT)
describe(AgreeT)
describe(ExtraT)
describe(ConscT)
describe(OpenT)
describe(IERT)
describe(WritT)
describe(WritFT)
describe(WritDT)
describe(OverT)
describe(OverFT)
describe(OverDT)
describe(ProAT)
describe(EnvFT)
describe(OPFT)
describe(ProET)
describe(ProSocT)
describe(PPT)
describe(PNT)
describe(FPT)
describe(PHT)
describe(PFT)
describe(VFICT)
describe(GPA)
sink()