OPFocus = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\OPFocus.csv",head=TRUE,sep=","))
OverallFuture = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\OverallFuture.csv",head=TRUE,sep=","))
ProAttRating = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\ProAttRating.csv",head=TRUE,sep=","))
WritingFuture = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\WritingFuture.csv",head=TRUE,sep=","))
WordCount = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\WordCount.csv",head=TRUE,sep=","))
EnvFocus = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\EnvFocus.csv",head=TRUE,sep=","))
IntExtRating = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\IntExtRating.csv",head=TRUE,sep=","))
OverallDaily = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\OverallDaily.csv",head=TRUE,sep=","))
WritingDaily = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\WritingDaily.csv",head=TRUE,sep=","))

hist(as.vector(OPFocus),breaks = 5,main = NULL, xlab = "Focus on Other People")
hist(as.vector(OverallFuture),breaks = 10,main = NULL, xlab = "Overall Future")
hist(as.vector(ProAttRating),breaks = 5,main = NULL, xlab = "Prosocial Attitudes")
hist(as.vector(WritingFuture),breaks = 10,main = NULL, xlab = "Writing Future")
hist(as.vector(EnvFocus),breaks = 5,main = NULL, xlab = "Environmental Focus")
hist(as.vector(IntExtRating),breaks = 2,main = NULL, xlab = "Internalization")