OPFocus = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\OPFocus.csv",head=TRUE,sep=","))
OverallFuture = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\OverallFuture.csv",head=TRUE,sep=","))
ProAttRating = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\ProAttRating.csv",head=TRUE,sep=","))
WritingFuture = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\WritingFuture.csv",head=TRUE,sep=","))
EnvFocus = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\EnvFocus.csv",head=TRUE,sep=","))
IntExtRating = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\IntExtRating.csv",head=TRUE,sep=","))
OverallDaily = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\OverallDaily.csv",head=TRUE,sep=","))
WritingDaily = as.matrix(read.csv(file="C:\\Users\\Eric Leingang\\Desktop\\Final Paper\\Variable Data\\WritingDaily.csv",head=TRUE,sep=","))

library(irr)
library(psych)

sink("interraterrealiabilities.txt")
icc(OverallFuture,"twoway","consistency")
icc(OverallDaily,"twoway","consistency")
kappam.fleiss(IntExtRating)
icc(WritingFuture,"twoway","consistency")
icc(WritingDaily,"twoway","consistency")
icc(ProAttRating,"twoway","consistency")
icc(OPFocus,"twoway","consistency")
icc(EnvFocus,"twoway","consistency")
sink()